#!/bin/sh
#
# Lithium: the most rad php framework
#
# @copyright     Copyright 2010, Union of RAD (http://union-of-rad.org)
# @license       http://opensource.org/licenses/bsd-license.php The BSD License
#
SELF=$0; test -L $0 && SELF=$(readlink -n $0)
php -f ${SELF/%li3/}lithium.php -- "$@"
