<?php
/**
 * Lithium: the most rad php framework
 *
 * @copyright     Copyright 2010, Union of RAD (http://union-of-rad.org)
 * @license       http://opensource.org/licenses/bsd-license.php The BSD License
 */

namespace lithium\tests\integration\data;

use \Exception;
use \ArrayAccess;
use \lithium\data\Connections;

class Company extends \lithium\data\Model {

	protected $_meta = array(
		'connection' => 'test',
		'source' => 'companies'
	);

	public static function classes() {
		return static::_instance()->_classes;
	}
}

class SourceTest extends \lithium\test\Unit {

	public $companyData = array(
		array('name' => 'BigBoxMart'),
		array('name' => 'Ma \'n Pa\'s Data Warehousing & Bait Shop')
	);

	public function setUp() {
		Company::__init();
	}

	public function tearDown() {
		try {
			foreach (Company::all() as $company) {
				$company->delete();
			}
		} catch (Exception $e) {
		}
	}

	/**
	 * Skip the test if no test database connection available.
	 *
	 * @return void
	 */
	public function skip() {
		$isAvailable = (
			Connections::get('test', array('config' => true)) &&
			Connections::get('test')->isConnected(array('autoConnect' => true))
		);
		$this->skipIf(!$isAvailable, "No test connection available");
	}

	/**
	 * Tests that a single record with a manually specified primary key can be created, persisted
	 * to an arbitrary data store, re-read and updated.
	 *
	 * @return void
	 */
	public function testSingleReadWriteWithKey() {
		$key = Company::meta('key');
		$classes = Company::classes();

		$new = Company::create(array($key => 12345, 'name' => 'Acme, Inc.'));
		$this->assertTrue(is_a($new, $classes['record']));

		$result = $new->data();
		$expected = array($key => 12345, 'name' => 'Acme, Inc.');
		$this->assertEqual($expected[$key], $result[$key]);
		$this->assertEqual($expected['name'], $result['name']);

		$this->assertFalse($new->exists());
		$this->assertTrue($new->save());
		$this->assertTrue($new->exists());

		$existing = Company::find(12345);
		$result = $existing->data();
		$this->assertEqual($expected[$key], $result[$key]);
		$this->assertEqual($expected['name'], $result['name']);
		$this->assertTrue($existing->exists());

		$existing->name = 'Big Brother and the Holding Company';
		$this->assertTrue($existing->save());

		$existing = Company::find(12345);
		$result = $existing->data();
		$expected['name'] = 'Big Brother and the Holding Company';
		$this->assertEqual($expected[$key], $result[$key]);
		$this->assertEqual($expected['name'], $result['name']);

		$existing->delete();
	}

	public function testReadWriteMultiple() {
		$companies = array();
		$key = Company::meta('key');

		foreach ($this->companyData as $data) {
			$companies[] = Company::create($data);
			$this->assertTrue($companies[count($companies) - 1]->save());
			$this->assertTrue($companies[count($companies) - 1]->{$key});
		}

		$all = Company::all();

		$expected = count($this->companyData);
		$this->assertEqual($expected, $all->count());
		$this->assertEqual($expected, count($all));

		$id = (string) $all->first()->{$key};
		$this->assertTrue(strlen($id) > 0);
        $this->assertTrue($all->data());

		foreach ($companies as $company) {
			$this->assertTrue($company->delete());
		}
	}

	public function testRecordOffset() {
		foreach ($this->companyData as $data) {
			Company::create($data)->save();
		}
		$all = Company::all();

		$result = $all->first();
		$this->skipIf(!$result instanceof ArrayAccess, 'Class does not implement ArrayAccess');

		$expected = 'BigBoxMart';
		$this->assertEqual($expected, $result['name']);

		$result = $result->data();
		$this->assertEqual($expected, $result['name']);

		$result = $all[1];
		$expected = 'Ma \'n Pa\'s Data Warehousing & Bait Shop';
		$this->assertEqual($expected, $result['name']);

		$result = $result->data();
		$this->assertEqual($expected, $result['name']);

		$this->assertNull($all[2]);
	}

	/**
	 * Tests that a record can be created, saved, and subsequently re-read using a key
	 * auto-generated by the data source. Uses short-hand `find()` syntax which does not support
	 * compound keys.
	 *
	 * @return void
	 */
	public function testGetRecordByGeneratedId() {
		$key = Company::meta('key');
		$company = Company::create(array('name' => 'Test Company'));
		$this->assertTrue($company->save());

		$id = $company->{$key};
		$companyCopy = Company::find($id);
		$this->assertEqual($company->data(), $companyCopy->data());
	}
}

?>