#!/bin/sh
#
# li₃: the most RAD framework for PHP (http://li3.me)
#
# Copyright 2016, Union of RAD. All rights reserved. This source
# code is distributed under the terms of the BSD 3-Clause License.
# The full license text can be found in the LICENSE.txt file.
#

SELF=$0; test -L "$0" && SELF=$(readlink -n $0)
php -f "$(dirname "$SELF")"/lithium.php -- "$@"
